version: "3.8"
services:
  geoserver:
    image: kartoza/geoserver:2.23.2
    container_name: geoserver
    restart: unless-stopped
    env_file: ./geoserver.env
    ports:
      - "8600:8080"
    volumes:
      - ./data_dir:/opt/geoserver/data_dir
      - ./styles:/opt/geoserver/data_dir/styles
      - ./extensions:/opt/geoserver/exts           # <— plugin ZIPs go here
      - ./lib/mysql-connector-java-8.0.28.jar:/opt/geoserver/webapps/geoserver/WEB-INF/lib/mysql-connector-java-8.0.28.jar  # <— JDBC driver mounted in
    environment:
      - GEOSERVER_INSTALL_EXTENSIONS=true
      - GEOSERVER_CORS_ENABLED=true
      - CORS_ALLOWED_ORIGINS=*
    extra_hosts:
      - "host.docker.internal:host-gateway"
